name: Continuous integration example

on: 
  workflow_dispatch:

jobs:

  test:
    strategy:
      fail-fast: false
      matrix: 
        os: [macos-latest,windows-latest,ubuntu-latest]
        java: ['11','17','21']
    runs-on: ${{matrix.os}}
    name: Java ${{matrix.java}} sample
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}
      - run: mvn test
